# GitHub Sponsors 및 기부 정보
# 이 파일을 사용하려면 .github 디렉토리를 생성하고 이 파일을 배치하세요

# GitHub Sponsors
# github: [yourusername]

# Ko-fi (한국 사용자에게 친숙)
# ko_fi: yourusername

# Patreon
# patreon: yourusername

# Open Collective
# open_collective: anonymous-torrent-stack

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/yourusername']

# 또는 여러 옵션 제공
# custom: ['https://www.paypal.me/yourusername', 'https://toss.me/yourusername']
